JID_OWNER="wyliodrin_test@wyliodrin.org"
JID_BOARD="wyliodrin_board@wyliodrin.org"
PASSWORD="wyliodrin"

sim_owner:
	/usr/bin/python3 sim_owner.py -d --jid $(JID_OWNER) --password $(PASSWORD) --to $(JID_BOARD)
